### ISSUE TITLE
Current fade distance is still rather high.

### ISSUE THREAD

**Issue by MagentaIris** [remghoost/LagFixPlugin#1]
Hi hi, Apologies in advance.

This isn't exactly an "Issue" so to say. But i wanted to note on older hardware the current corpse float point value of 55f is still too high.

May I suggest releasing an alternate build with the value set to around 25f or 30f?

I personally dont care if corpses fade while in-view, My performance is much more important to me.

Thanks for creating this in the first place by the way, I'd build a 25/30 one myself but having to regrab all the visual studio stuff and what not is a pain.

Thanks for reading too!

**Comment by remghoost** [comment]
Yeah, no worries. 
I can rebuild you a version that has it at 25f.

I was planning on exposing that variable in the options menu (so the user could adjust it as they see fit), but I never got around to it.

I had it set at 55f because that was about where I walked out the fog to be and any closer would cause pop-in.
But I could see wanting to set it lower for performance reasons.

Mostly stepping back from modding this game though, since the community has apparently decided that BepInEx 5.4.23.2 is the version they want to use (or rather, one person has) and I don't feel like going through and backporting my mods to it. haha.

Might change my mind later, but it kind of took the wind out of my sails.

**I'll upload a release that has it set at 25f and link it in this issue.**

**Comment by remghoost** [comment]
[Here you go.](https://github.com/remghoost/LagFixPlugin/releases/tag/0.9.0.1)

I built two different versions (one at 25f, one at 30f).

It should work fine (since I only changed that variable), but let me know if it doesn't.
You'll know it's working properly (and that I uploaded the correct exports haha) if you see the bodies pop-in.

**Comment by MagentaIris** [comment]
> [Here you go.](https://github.com/remghoost/LagFixPlugin/releases/tag/0.9.0.1)
> 
> I built two different versions (one at 25f, one at 30f).
> 
> It should work fine (since I only changed that variable), but let me know if it doesn't. You'll know it's working properly (and that I uploaded the correct exports haha) if you see the bodies pop-in.

Woah, Thank you so much for the fast reply.

I do agree that exposing it as a CVar (Console Variable) or just a simple moddable variable in the options would be incredibly helpful, specially mid-run if people are getting too many frame drops.

❤

**Comment by remghoost** [comment]
Also, if you want, I can build you an even more aggressive one (setting the variable to like 10f or something).
It's no worries.

>specially mid-run if people are getting too many frame drops.

**Actually, that raises a potentially interesting addition to the mod.**
It could dynamically watch the framerate and adjust the culling distance automatically if the number of dead enemies reaches a certain threshold (to ensure it's the enemies that are causing the framerate problems).

Hmmm....

**Comment by MagentaIris** [comment]
> Also, if you want, I can build you an even more aggressive one (setting the variable to like 10f or something). It's no worries.
> 
> > specially mid-run if people are getting too many frame drops.
> 
> **Actually, that raises a potentially interesting addition to the mod.** It could dynamically watch the framerate and adjust the culling distance automatically if the number of dead enemies reaches a certain threshold (to ensure it's the enemies that are causing the framerate problems).
> 
> Hmmm....

I am so late to this holy heck. Making 2 outputs would be pretty simple i'm sure. Maybe even just creating a graph UI that lets you left click pointer sets which then just dynamically lerps between the values.

So if i left click on (120 FPS = Corpse Range 50) then left click on (30 FPS = Corpse Range 15) it would lerp between these 2 values if its between 30 fps and 120 fps, and obviously cap at 50 if fps is above or equal to 120, and minimum cap at 30 fps or below.

Personally i think just allowing the player to modify the value in the options menu with a slider is more than enough!

**Comment by remghoost** [comment]
I was more so picturing the mod watching the framerate and dynamically adjusting the culling range based on that (to a lower threshold), since it seemed like the body count was the biggest culprit of the dip in framerate.

Making the variable exposed to the player would be a decent way to go about it though.
Or even just a config file that the mod would read on startup to get the value.

I suppose you could make a graph and allow players to pick their limits, but that seems like a heck of a lot of work for something that already mostly works... haha. If you wanna give it a whack, go for it.

But I haven't touched this game in months, so it's all just speculation on my part.
